In [14]:
documents = ["This little cat came to play when I was eating at a restaurant. I had to take a photo.",
             "Merley has the best squooshy kitten belly.",
             "Google Translate app is incredible.",
             "If you open 100 tabs in google chrome you get a smiley face.",
             "Best cat photo I've ever taken.",
             "Climbing ninja cat.",
             "Impressed with the current version of the google translate app.",
             "Key promoter extension for Google Chrome."]

In [15]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import re
from nltk.tokenize import word_tokenize
#from nltk.stem import WordNetLemmatizer


In [16]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
def text_preprocesser(text):
    text= re.sub(r'\W',' ', text)
    tokens = word_tokenize(text.lower())
    tokens = [token for token in tokens if token not in stopwords.words('english')]
    tokens = [word for word in tokens if len(word)>=3]
    preprocessed_text = ' '.join(tokens)
    return preprocessed_text 

In [18]:
text_preprocesser(documents[0])

'little cat came play eating restaurant take photo'

In [19]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

Count_vectorizer = CountVectorizer(preprocessor=text_preprocesser)

In [21]:
#Count_vectorizer

In [22]:
cv=Count_vectorizer.fit_transform(documents)

In [23]:
cv.todense()

matrix([[0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
         0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
         0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
import pandas as pd
df_cv = pd.DataFrame(cv.toarray().transpose(), index = Count_vectorizer.get_feature_names())

In [25]:
df_cv

0  1  2  3  4  5  6  7
100         0  0  0  1  0  0  0  0
app         0  0  1  0  0  0  1  0
belly       0  1  0  0  0  0  0  0
best        0  1  0  0  1  0  0  0
came        1  0  0  0  0  0  0  0
cat         1  0  0  0  1  1  0  0
chrome      0  0  0  1  0  0  0  1
climbing    0  0  0  0  0  1  0  0
current     0  0  0  0  0  0  1  0
eating      1  0  0  0  0  0  0  0
ever        0  0  0  0  1  0  0  0
extension   0  0  0  0  0  0  0  1
face        0  0  0  1  0  0  0  0
get         0  0  0  1  0  0  0  0
google      0  0  1  1  0  0  1  1
impressed   0  0  0  0  0  0  1  0
incredible  0  0  1  0  0  0  0  0
key         0  0  0  0  0  0  0  1
kitten      0  1  0  0  0  0  0  0
little      1  0  0  0  0  0  0  0
merley      0  1  0  0  0  0  0  0
ninja       0  0  0  0  0  1  0  0
open        0  0  0  1  0  0  0  0
photo       1  0  0  0  1  0  0  0
play        1  0  0  0  0  0  0  0
promoter    0  0  0  0  0  0  0  1
restaurant  1  0  0  0  0  0  0  0
smiley      0  0  0  1  0  0  0  0
squooshy    0  1  0  0  0  0  0  0
tabs        0  0  0  1  0  0  0  0
take        1  0  0  0  0  0  0  0
taken       0  0  0  0  1  0  0  0
translate   0  0  1  0  0  0  1  0
version     0  0  0  0  0  0  1  0

In [26]:
tfidf_vectorizer = TfidfVectorizer(preprocessor=text_preprocesser)

In [27]:
tfidf_vectorizer

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2',
                preprocessor=<function text_preprocesser at 0x7ff4f9065f80>,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [28]:
tfidf = tfidf_vectorizer.fit_transform(documents)

In [41]:
df= pd.DataFrame(tfidf.toarray().transpose(), index=tfidf_vectorizer.get_feature_names())

In [44]:
df

doc1      doc2      doc3      doc4      doc5      doc6  \
100         0.000000  0.000000  0.000000  0.375176  0.000000  0.000000   
app         0.000000  0.000000  0.500240  0.000000  0.000000  0.000000   
belly       0.000000  0.461149  0.000000  0.000000  0.000000  0.000000   
best        0.000000  0.386479  0.000000  0.000000  0.422875  0.000000   
came        0.372023  0.000000  0.000000  0.000000  0.000000  0.000000   
cat         0.269044  0.000000  0.000000  0.000000  0.364907  0.455297   
chrome      0.000000  0.000000  0.000000  0.314427  0.000000  0.000000   
climbing    0.000000  0.000000  0.000000  0.000000  0.000000  0.629565   
current     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
eating      0.372023  0.000000  0.000000  0.000000  0.000000  0.000000   
ever        0.000000  0.000000  0.000000  0.000000  0.504577  0.000000   
extension   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
face        0.000000  0.000000  0.000000  0.375176  0.000000  0.000000   
get         0.000000  0.000000  0.000000  0.375176  0.000000  0.000000   
google      0.000000  0.000000  0.378476  0.237892  0.000000  0.000000   
impressed   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
incredible  0.000000  0.000000  0.596889  0.000000  0.000000  0.000000   
key         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
kitten      0.000000  0.461149  0.000000  0.000000  0.000000  0.000000   
little      0.372023  0.000000  0.000000  0.000000  0.000000  0.000000   
merley      0.000000  0.461149  0.000000  0.000000  0.000000  0.000000   
ninja       0.000000  0.000000  0.000000  0.000000  0.000000  0.629565   
open        0.000000  0.000000  0.000000  0.375176  0.000000  0.000000   
photo       0.311784  0.000000  0.000000  0.000000  0.422875  0.000000   
play        0.372023  0.000000  0.000000  0.000000  0.000000  0.000000   
promoter    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
restaurant  0.372023  0.000000  0.000000  0.000000  0.000000  0.000000   
smiley      0.000000  0.000000  0.000000  0.375176  0.000000  0.000000   
squooshy    0.000000  0.461149  0.000000  0.000000  0.000000  0.000000   
tabs        0.000000  0.000000  0.000000  0.375176  0.000000  0.000000   
take        0.372023  0.000000  0.000000  0.000000  0.000000  0.000000   
taken       0.000000  0.000000  0.000000  0.000000  0.504577  0.000000   
translate   0.000000  0.000000  0.500240  0.000000  0.000000  0.000000   
version     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

                doc7      doc8  
100         0.000000  0.000000  
app         0.382258  0.000000  
belly       0.000000  0.000000  
best        0.000000  0.000000  
came        0.000000  0.000000  
cat         0.000000  0.000000  
chrome      0.000000  0.413674  
climbing    0.000000  0.000000  
current     0.456112  0.000000  
eating      0.000000  0.000000  
ever        0.000000  0.000000  
extension   0.000000  0.493598  
face        0.000000  0.000000  
get         0.000000  0.000000  
google      0.289212  0.312981  
impressed   0.456112  0.000000  
incredible  0.000000  0.000000  
key         0.000000  0.493598  
kitten      0.000000  0.000000  
little      0.000000  0.000000  
merley      0.000000  0.000000  
ninja       0.000000  0.000000  
open        0.000000  0.000000  
photo       0.000000  0.000000  
play        0.000000  0.000000  
promoter    0.000000  0.493598  
restaurant  0.000000  0.000000  
smiley      0.000000  0.000000  
squooshy    0.000000  0.000000  
tabs        0.000000  0.000000  
take        0.000000  0.000000  
taken       0.000000  0.000000  
translate   0.382258  0.000000  
version     0.456112  0.000000

In [42]:
df.columns = ['doc1', 'doc2', 'doc3', 'doc4','doc5', 'doc6', 'doc7', 'doc8']

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
df['doc1'].values.reshape(1, -1).shape

(1, 34)

In [34]:
for i in range(1, 9):
    globals()["txt" + str(i)] =df[df.columns[i-1]].values.reshape(1, -1)  

In [35]:
txt3

array([[0.        , 0.50023967, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.37847576,
        0.        , 0.59688913, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.50023967, 0.        ]])

In [36]:
print("Similarity txt1 and txt2:", cosine_similarity(txt1, txt2))

Similarity txt1 and txt2: [[0.]]


In [37]:
print("Similarity txt3 and txt7:", cosine_similarity(txt3, txt7))

Similarity txt3 and txt7: [[0.49190046]]


In [38]:
print("Similarity txt1 and txt3:", cosine_similarity(txt1, txt5))

Similarity txt1 and txt3: [[0.23002174]]


In [39]:
print("Similarity txt1 and txt7:", cosine_similarity(df['doc1'].values.reshape(1, -1), df['doc6'].values.reshape(1, -1)))

Similarity txt1 and txt7: [[0.12249497]]


In [40]:
txt7

array([[0.        , 0.38225757, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.45611213, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.28921181,
        0.45611213, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.38225757, 0.45611213]])